name: ✨ 提出建议
description: 纯提建议的issue
labels: []
body:
    - type: markdown
      attributes:
          value: |
              请尽量描述清楚你的建议，这将帮助我们更好地理解和评估。

              > **注意**：插件相关的功能请求请勿在此提交，另外，提交问题请去另一个模板。

    - type: checkboxes
      id: checklist
      attributes:
          label: 提交前确认
          options:
              - label: 我已搜索过现有 Issues，确认没有重复的请求
                required: true

    - type: textarea
      id: problem
      attributes:
          label: 建议
          description: 描述你想解决的问题或不便之处
          placeholder: '希望 ... '
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: 期望的方案
          description: 描述你期望的功能或解决方案
      validations:
          required: false

    - type: textarea
      id: alternatives
      attributes:
          label: 替代方案
          description: 描述你考虑过的其他替代方案（如有）
      validations:
          required: false

    - type: textarea
      id: additional
      attributes:
          label: 补充信息
          description: 其他可能有帮助的截图或信息
      validations:
          required: false